author: Lauren Bodnar
title: Lauren Bodnar | Blog
logo: /img/logo/white/white-logo-no-tagline.png
subtitle: Think Deeply | Live Fully
description: My personal blog and thoughts about life, family, books, and Christianity.
url: /
root: /

# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
 - category
 - tagcloud
 - archive
theme: 'laurens-theme'
# widget behavior
archive_type: 'monthly'
show_count: false
archive_generator:
  per_page: 0
  yearly: true
  monthly: true
  daily: false
  order_by: -date

highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:

theme_config:
  welcome_cover: /img/welcome_cover.jpg
  menu:
    GitHub: https://github.com/laurenbodnar
    Archives: /archives
  social:
    Github: https://github.com/laurenbodnar

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
instagram: lauren.n.bodnar
google_plus:
fb_admins:
fb_app_id:

instagramWall:
  enable: true
  requestedCount: 12
  itemsPerRow: 4
  showCaption: true
  displayStyle: 'flex'
  gutterSize: '10px'
  overlayColor: 'black'
  textColor: 'white'

all_minifier: false

skip_render:
  - "*admin/*"

netlify_cms:
  backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)

  # This line should *not* be indented
  publish_mode: editorial_workflow

  # This line should *not* be indented
  media_folder: "source/img" # Media files will be stored in the repo under images/uploads
  public_folder: "/img"
