author: Lauren Bodnar
title: Lauren Bodnar | Blog
subtitle: Think Deeply | Live Fully
url: /
root: /

# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
 - tagcloud
# - archive
theme: 'Material-T'
# widget behavior
archive_type: 'monthly'
show_count: false
archive_generator:
  per_page: 0
  yearly: true
  monthly: true
  daily: false
  order_by: -date

highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:

theme_config:
  welcome_cover: /img/welcome_cover.jpg
  menu:
    Test: /2019/03/06/hello-world/
    GitHub: https://github.com/laurenbodnar
    Archives: /archives
  social:
    Github: https://github.com/laurenbodnar

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:

deploy:
  type: git
  repo: git@github.com:laurenbodnar/laurenbodnar.com.git  #https://bitbucket.org/JohnSmith/johnsmith.bitbucket.io
  branch: gh-pages #published
  #message: [message]  #leave this blank
